### ISSUE TITLE
Normal/All Creative Tabs Are Not Working

### ISSUE THREAD

**Issue by CamCam5701** [Spectrall368/Generator-1.19.2#15]
I'm pretty sure the normal creative tabs are not working, not the custom ones (I'm pretty sure) because when I got errors on literally every item and block or what ever I went to this one block (the Cheese Block) and removed its normal creative inventory tabs, NOT the modded one and the error for it went away. Below will be some of the errors I'm getting

Executing Gradle task: build 
Build info: MCreator 2025.1.13416, forge-1.19.2, 64-bit, 32094 MB, Windows 11, JVM 21.0.5, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2025-06-07-08:36:08 
 
 
BUILD FAILED 
Task completed in 19 seconds 
 
Calculating task graph as configuration cache cannot be reused because environment variable 'MCREATOR_JVM_OPTIONS' has changed. 
> Task :jarJar NO-SOURCE 
> Task :processTestResources NO-SOURCE 
> Task :createMinecraftArtifacts UP-TO-DATE 
> Task :processResources UP-TO-DATE 
> Task :compileJava FAILED 
[C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\init\CheesemodModItems.java:106](file:///C:/Users/camer/MCreatorWorkspaces/Cheese_Mod_Test/src/main/java/cheesemod/init/CheesemodModItems.java:106): error: variable CHEESE_BOSS_SPAWN_EGG is already defined in class CheesemodModItems 
    public static final RegistryObject<Item> CHEESE_BOSS_SPAWN_EGG = REGISTRY.register("cheese_boss_spawn_egg", 
                                             ^ 
[C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\init\CheesemodModItems.java:108](file:///C:/Users/camer/MCreatorWorkspaces/Cheese_Mod_Test/src/main/java/cheesemod/init/CheesemodModItems.java:108): error: variable BETTER_CHEESE_BOSS_SPAWN_EGG is already defined in class CheesemodModItems 
    public static final RegistryObject<Item> BETTER_CHEESE_BOSS_SPAWN_EGG = REGISTRY.register("better_cheese_boss_spawn_egg", 
                                             ^ 
[C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\init\CheesemodModItems.java:110](file:///C:/Users/camer/MCreatorWorkspaces/Cheese_Mod_Test/src/main/java/cheesemod/init/CheesemodModItems.java:110): error: variable CHEESE_UPGRADER is already defined in class CheesemodModItems 
    public static final RegistryObject<Item> CHEESE_UPGRADER = block(CheesemodModBlocks.CHEESE_UPGRADER, CheesemodModTabs.TAB_MODDED_STUFF, CreativeModeTab.TAB_TRANSPORTATION); 
                                             ^

C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\client\gui\CheeseGunOrBazookaDowngraderGUIScreen.java:63: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
        RenderSystem.setShaderTexture(0, new ResourceLocation("cheesemod:textures/screens/anvil.png")); 
                                         ^ 
C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\client\gui\CheeseGunOrBazookaDowngraderGUIScreen.java:66: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
        RenderSystem.setShaderTexture(0, new ResourceLocation("cheesemod:textures/screens/checkbox.png")); 
                                         ^ 
C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\client\gui\CheeseGunOrBazookaDowngraderGUIScreen.java:69: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
        RenderSystem.setShaderTexture(0, new ResourceLocation("cheesemod:textures/screens/blue_cheese_bazooka.png")); 
                                         ^

[C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\init\CheesemodModItems.java:53](file:///C:/Users/camer/MCreatorWorkspaces/Cheese_Mod_Test/src/main/java/cheesemod/init/CheesemodModItems.java:53): error: method block in class CheesemodModItems cannot be applied to given types; 
    public static final RegistryObject<Item> GRASS_BLOCK_BUT_BETTER = block(CheesemodModBlocks.GRASS_BLOCK_BUT_BETTER, CheesemodModTabs.TAB_MODDED_STUFF, CreativeModeTab.TAB_DECORATIONS, CreativeModeTab.TAB_BUILDING_BLOCKS); 
                                                                      ^ 
  required: RegistryObject<Block>,CreativeModeTab 
  found:    RegistryObject<Block>,CreativeModeTab,CreativeModeTab,CreativeModeTab 
  reason: actual and formal argument lists differ in length 
[C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\init\CheesemodModItems.java:54](file:///C:/Users/camer/MCreatorWorkspaces/Cheese_Mod_Test/src/main/java/cheesemod/init/CheesemodModItems.java:54): error: method block in class CheesemodModItems cannot be applied to given types; 
    public static final RegistryObject<Item> YOU_THOUGHT = block(CheesemodModBlocks.YOU_THOUGHT, CheesemodModTabs.TAB_MODDED_STUFF, CreativeModeTab.TAB_BUILDING_BLOCKS); 
                                                           ^ 
  required: RegistryObject<Block>,CreativeModeTab 
  found:    RegistryObject<Block>,CreativeModeTab,CreativeModeTab 
  reason: actual and formal argument lists differ in length 
[C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\init\CheesemodModItems.java:55](file:///C:/Users/camer/MCreatorWorkspaces/Cheese_Mod_Test/src/main/java/cheesemod/init/CheesemodModItems.java:55): error: method block in class CheesemodModItems cannot be applied to given types; 
    public static final RegistryObject<Item> YOU_REALLY_TRIED_THIS = block(CheesemodModBlocks.YOU_REALLY_TRIED_THIS, CheesemodModTabs.TAB_MODDED_STUFF, CreativeModeTab.TAB_BUILDING_BLOCKS); 
                                                                     ^ 
  required: RegistryObject<Block>,CreativeModeTab 
  found:    RegistryObject<Block>,CreativeModeTab,CreativeModeTab 
  reason: actual and formal argument lists differ in length

C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\procedures\CheeseSummonerOnBlockRightClickedProcedure.java:126: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
                                                        _level.playLocalSound(x, y, z, ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("entity.experience_orb.pickup")), SoundSource.NEUTRAL, 1, 1, false); 
                                                                                                                             ^ 
C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\procedures\CheeseSummonerOnBlockRightClickedProcedure.java:134: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
                                                            _level.playSound(null, new BlockPos(x, y, z), ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("entity.experience_orb.pickup")), SoundSource.NEUTRAL, 1, 1); 
                                                                                                                                                ^ 
C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\procedures\CheeseSummonerOnBlockRightClickedProcedure.java:136: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
                                                            _level.playLocalSound(x, y, z, ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("entity.experience_orb.pickup")), SoundSource.NEUTRAL, 1, 1, false); 
                                                                                                                                 ^

C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\procedures\CheeseSummonerOnBlockRightClickedProcedure.java:245: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
                                    _level.playLocalSound(x, y, z, ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("entity.experience_orb.pickup")), SoundSource.NEUTRAL, 1, 1, false); 
                                                                                                         ^ 
C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\procedures\CheeseSummonerOnBlockRightClickedProcedure.java:253: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
                                        _level.playSound(null, new BlockPos(x, y, z), ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("entity.experience_orb.pickup")), SoundSource.NEUTRAL, 1, 1); 
                                                                                                                            ^ 
C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\procedures\CheeseSummonerOnBlockRightClickedProcedure.java:255: warning: [removal] ResourceLocation(String) in ResourceLocation has been deprecated and marked for removal 
                                        _level.playLocalSound(x, y, z, ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation("entity.experience_orb.pickup")), SoundSource.NEUTRAL, 1, 1, false); 
                                                                                                             ^ 
Note: C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\procedures\CheeseSummonerOnBlockRightClickedProcedure.java has additional uses or overrides of a deprecated API that is marked for removal. 
100 errors 
100 warnings 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler output below. 
[C:\Users\camer\MCreatorWorkspaces\Cheese_Mod_Test\src\main\java\cheesemod\init\CheesemodModItems.java:106](file:///C:/Users/camer/MCreatorWorkspaces/Cheese_Mod_Test/src/main/java/cheesemod/init/CheesemodModItems.java:106): error: variable CHEESE_BOSS_SPAWN_EGG is already defined in class CheesemodModItems 
      public static final RegistryObject<Item> CHEESE_BOSS_SPAWN_EGG = REGISTRY.register("cheese_boss_spawn_egg", 
                                               ^ 
  100 errors 
  100 warnings 
* Try: 
> Check your code and dependencies to fix the compilation error(s) 
> Run with --scan to get full insights. 
BUILD FAILED in 2s 
3 actionable tasks: 1 executed, 2 up-to-date 
Configuration cache entry stored. 
 
BUILD FAILED 
Task completed in 6 seconds

**Comment by Spectrall368** [comment]
I have no errors, could you send me the workspace?

**Comment by CamCam5701** [comment]
I’ll send you the workspace when I get home

**Comment by CamCam5701** [comment]
Didn’t mean to close

**Comment by Spectrall368** [comment]
Ok thank you

**Comment by CamCam5701** [comment]
(it failed to upload 1 sec)

sorry for the late response, I've been busy but here ya go (2025.1 1.19.2)

can I just send a google drive file of it?

**Comment by CamCam5701** [comment]
and just a side note this issue does happen on your 1.18.2 plugin and when I took off the vanilla creative inventory tabs it worked for that item so yeah

**Comment by Spectrall368** [comment]
> can I just send a google drive file of it?

Yes

**Comment by CamCam5701** [comment]
here ya go https://drive.google.com/file/d/1gholPIFpCBZ-kRXrwpj5mUhCE_8hsdWc/view?usp=drive_link

**Comment by Spectrall368** [comment]
> here ya go https://drive.google.com/file/d/1gholPIFpCBZ-kRXrwpj5mUhCE_8hsdWc/view?usp=drive_link

Thank you, i will review it tomorrow

**Comment by CamCam5701** [comment]
Ok, take your time

**Comment by Spectrall368** [comment]
Closed #15 as completed via [4d32de3](https://github.com/Spectrall368/Generator-1.19.2/commit/4d32de3e4a6608a9592fca9174336cd4cbae9ae5).

**Comment by Spectrall368** [comment]
Just to remind you, 1.19.2 items don't support multiple creative tabs.

**Comment by Spectrall368** [comment]
Just re-download the 1.8 version and regenerate the items code
![Image](https://github.com/user-attachments/assets/5af1b770-0eb5-4e54-9eaa-15f09cca4548)

**Comment by CamCam5701** [comment]
Ok now it works and the build doesn't fail but the items and stuff don't pop up in modded creative tab inventories as show in the images below

Same thing with your 1.18.2 forge plugin --keep up the good work though!

![Image](https://github.com/user-attachments/assets/b492f397-f2f0-4ac6-a536-4d84011924fa)
![Image](https://github.com/user-attachments/assets/4903181d-8d9e-42b8-b5cb-6425d2b8c0b9)

**Comment by Spectrall368** [comment]
> Ok now it works and the build doesn't fail but the items and stuff don't pop up in modded creative tab inventories as show in the images below
> 
> Same thing with your 1.18.2 forge plugin --keep up the good work though!


1.19.2 items don't support multiple creative tabs.

**Comment by Spectrall368** [comment]
> Ok now it works and the build doesn't fail but the items and stuff don't pop up in modded creative tab inventories as show in the images below
> 
> Same thing with your 1.18.2 forge plugin --keep up the good work though!
> 

This happens in my side (I just downloaded the generator again from the mcreator site)

![Image](https://github.com/user-attachments/assets/3b9d499e-a187-468c-a26d-12f8784b6c35)

**Comment by Spectrall368** [comment]
1.19.2 items don't support multiple creative tabs.

Example, in this case only the last tab will be considered

![Image](https://github.com/user-attachments/assets/85442b60-1a54-479a-8fcc-84112b66a4d0)

**Comment by CamCam5701** [comment]
ok I moved the modded stuff tab to the end and kept all the other stuff so all the tabs show up in other versions of the mod but it keeps mixing it up. Not the biggest issue but yeah

![Image](https://github.com/user-attachments/assets/4bde278d-72df-4645-b601-d80cbbad1da4)
![Image](https://github.com/user-attachments/assets/cbbfdf6d-39cb-4416-b7ce-3e2c5e412d99)

**Comment by Spectrall368** [comment]
> ok I moved the modded stuff tab to the end and kept all the other stuff so all the tabs show up in other versions of the mod but it keeps mixing it up. Not the biggest issue but yeah
> 

I will check later

**Comment by CamCam5701** [comment]
ok take your time

**Comment by Spectrall368** [comment]
> ok take your time

I fixed it, I need to optimize it and then i will release the fix

**Comment by Spectrall368** [comment]
Done, just re-download the 1.8 version again

**Comment by CamCam5701** [comment]
I did and I'm still having the same issue, I've cleared all caches and regenerated the code and build, I can send you another download of the workspace tomorrow through google drive probably I just have to go (my time zone is CST for reference)

![Image](https://github.com/user-attachments/assets/80463340-05c2-490c-8e77-29f591a1de34)

**Comment by Spectrall368** [comment]
> I did and I'm still having the same issue, I've cleared all caches and regenerated the code and build, I can send you another download of the workspace tomorrow through google drive probably I just have to go (my time zone is CST for reference)
>

Ok, anyway I tested with your workspace and it worked

**Comment by Spectrall368** [comment]
> I did and I'm still having the same issue, I've cleared all caches and regenerated the code and build, I can send you another download of the workspace tomorrow through google drive probably I just have to go (my time zone is CST for reference)
> 
you created a new world right? (if you order the taba and enter a world you will see the old order unlike the new one you will see if you make a new world)

**Comment by CamCam5701** [comment]
I just made a new world and it works now! Thank you so much!

**Comment by Spectrall368** [comment]
> I just made a new world and it works now! Thank you so much!

Good :)
